zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
kafka:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.0.15
    KAFKA_CREATE_TOPICS: "my-topic:1:1,Topic2:1:1,cameras:1:1"
    KAFKA_MESSAGE_MAX_BYTES: 30000000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
ui:
  image: hwestphal/kafka-web-console
  ports:
    - "9000:9000"
  links:
    - zookeeper:zk
    - kafka:kf
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /opt/kafka/kafka-ui/data:/data
